"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

// Comprehensive website translations
export const websiteTranslations = {
  en: {
    // Navigation
    guides: "Guides",
    travelers: "Travelers",
    trips: "Trips",
    myProfile: "My Profile",
    adminPage: "Admin Page",
    language: "Language",
    logout: "Log out",
    logIn: "Log In",

    // Homepage
    welcome: "Welcome to GuideMe",
    discover: "Discover Amazing Destinations",
    explore: "Explore the world with local guides",
    getStarted: "Get Started",
    learnMore: "Learn More",

    // Common
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    view: "View",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    loading: "Loading...",
    error: "Error",
    success: "Success",

    // Profile
    profile: "Profile",
    settings: "Settings",
    personalInfo: "Personal Information",
    email: "Email",
    phone: "Phone",
    location: "Location",
    bio: "Biography",
    updateProfile: "Update Profile",

    // Booking
    book: "Book",
    booking: "Booking",
    price: "Price",
    duration: "Duration",
    date: "Date",
    time: "Time",
    participants: "Participants",
    total: "Total",
    pay: "Pay",

    // Reviews
    reviews: "Reviews",
    rating: "Rating",
    writeReview: "Write Review",
    submitReview: "Submit Review",

    // Footer
    about: "About",
    contact: "Contact",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    support: "Support",

    // Admin
    dashboard: "Dashboard",
    users: "Users",
    statistics: "Statistics",
    reports: "Reports",
    manage: "Manage",
  },
  zh: {
    guides: "导游",
    travelers: "游客",
    trips: "旅行",
    myProfile: "我的资料",
    adminPage: "管理员页面",
    language: "语言",
    logout: "退出登录",
    logIn: "登录",
    welcome: "欢迎来到GuideMe",
    discover: "发现精彩目的地",
    explore: "与当地导游一起探索世界",
    getStarted: "开始使用",
    learnMore: "了解更多",
    search: "搜索",
    filter: "筛选",
    sort: "排序",
    view: "查看",
    edit: "编辑",
    delete: "删除",
    save: "保存",
    cancel: "取消",
    confirm: "确认",
    loading: "加载中...",
    error: "错误",
    success: "成功",
    profile: "个人资料",
    settings: "设置",
    personalInfo: "个人信息",
    email: "邮箱",
    phone: "电话",
    location: "位置",
    bio: "个人简介",
    updateProfile: "更新资料",
    book: "预订",
    booking: "预订",
    price: "价格",
    duration: "时长",
    date: "日期",
    time: "时间",
    participants: "参与者",
    total: "总计",
    pay: "支付",
    reviews: "评价",
    rating: "评分",
    writeReview: "写评价",
    submitReview: "提交评价",
    about: "关于",
    contact: "联系",
    privacy: "隐私政策",
    terms: "服务条款",
    support: "支持",
    dashboard: "仪表板",
    users: "用户",
    statistics: "统计",
    reports: "报告",
    manage: "管理",
  },
  ja: {
    guides: "ガイド",
    travelers: "旅行者",
    trips: "旅行",
    myProfile: "マイプロフィール",
    adminPage: "管理者ページ",
    language: "言語",
    logout: "ログアウト",
    logIn: "ログイン",
    welcome: "GuideMeへようこそ",
    discover: "素晴らしい目的地を発見",
    explore: "地元のガイドと一緒に世界を探索",
    getStarted: "始める",
    learnMore: "詳細を見る",
    search: "検索",
    filter: "フィルター",
    sort: "並び替え",
    view: "表示",
    edit: "編集",
    delete: "削除",
    save: "保存",
    cancel: "キャンセル",
    confirm: "確認",
    loading: "読み込み中...",
    error: "エラー",
    success: "成功",
    profile: "プロフィール",
    settings: "設定",
    personalInfo: "個人情報",
    email: "メール",
    phone: "電話",
    location: "場所",
    bio: "自己紹介",
    updateProfile: "プロフィール更新",
    book: "予約",
    booking: "予約",
    price: "価格",
    duration: "期間",
    date: "日付",
    time: "時間",
    participants: "参加者",
    total: "合計",
    pay: "支払い",
    reviews: "レビュー",
    rating: "評価",
    writeReview: "レビューを書く",
    submitReview: "レビューを投稿",
    about: "について",
    contact: "お問い合わせ",
    privacy: "プライバシーポリシー",
    terms: "利用規約",
    support: "サポート",
    dashboard: "ダッシュボード",
    users: "ユーザー",
    statistics: "統計",
    reports: "レポート",
    manage: "管理",
  },
  es: {
    guides: "Guías",
    travelers: "Viajeros",
    trips: "Viajes",
    myProfile: "Mi Perfil",
    adminPage: "Página de Admin",
    language: "Idioma",
    logout: "Cerrar Sesión",
    logIn: "Iniciar Sesión",
    welcome: "Bienvenido a GuideMe",
    discover: "Descubre Destinos Increíbles",
    explore: "Explora el mundo con guías locales",
    getStarted: "Comenzar",
    learnMore: "Saber Más",
    search: "Buscar",
    filter: "Filtrar",
    sort: "Ordenar",
    view: "Ver",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    profile: "Perfil",
    settings: "Configuración",
    personalInfo: "Información Personal",
    email: "Correo",
    phone: "Teléfono",
    location: "Ubicación",
    bio: "Biografía",
    updateProfile: "Actualizar Perfil",
    book: "Reservar",
    booking: "Reserva",
    price: "Precio",
    duration: "Duración",
    date: "Fecha",
    time: "Hora",
    participants: "Participantes",
    total: "Total",
    pay: "Pagar",
    reviews: "Reseñas",
    rating: "Calificación",
    writeReview: "Escribir Reseña",
    submitReview: "Enviar Reseña",
    about: "Acerca de",
    contact: "Contacto",
    privacy: "Política de Privacidad",
    terms: "Términos de Servicio",
    support: "Soporte",
    dashboard: "Panel",
    users: "Usuarios",
    statistics: "Estadísticas",
    reports: "Reportes",
    manage: "Gestionar",
  },
  de: {
    guides: "Führer",
    travelers: "Reisende",
    trips: "Reisen",
    myProfile: "Mein Profil",
    adminPage: "Admin-Seite",
    language: "Sprache",
    logout: "Abmelden",
    logIn: "Anmelden",
    welcome: "Willkommen bei GuideMe",
    discover: "Entdecke erstaunliche Ziele",
    explore: "Erkunde die Welt mit lokalen Führern",
    getStarted: "Loslegen",
    learnMore: "Mehr erfahren",
    search: "Suchen",
    filter: "Filter",
    sort: "Sortieren",
    view: "Anzeigen",
    edit: "Bearbeiten",
    delete: "Löschen",
    save: "Speichern",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    loading: "Lädt...",
    error: "Fehler",
    success: "Erfolg",
    profile: "Profil",
    settings: "Einstellungen",
    personalInfo: "Persönliche Informationen",
    email: "E-Mail",
    phone: "Telefon",
    location: "Standort",
    bio: "Biografie",
    updateProfile: "Profil aktualisieren",
    book: "Buchen",
    booking: "Buchung",
    price: "Preis",
    duration: "Dauer",
    date: "Datum",
    time: "Zeit",
    participants: "Teilnehmer",
    total: "Gesamt",
    pay: "Bezahlen",
    reviews: "Bewertungen",
    rating: "Bewertung",
    writeReview: "Bewertung schreiben",
    submitReview: "Bewertung absenden",
    about: "Über",
    contact: "Kontakt",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    support: "Support",
    dashboard: "Dashboard",
    users: "Benutzer",
    statistics: "Statistiken",
    reports: "Berichte",
    manage: "Verwalten",
  },
  ko: {
    guides: "가이드",
    travelers: "여행자",
    trips: "여행",
    myProfile: "내 프로필",
    adminPage: "관리자 페이지",
    language: "언어",
    logout: "로그아웃",
    logIn: "로그인",
    welcome: "GuideMe에 오신 것을 환영합니다",
    discover: "놀라운 목적지를 발견하세요",
    explore: "현지 가이드와 함께 세계를 탐험하세요",
    getStarted: "시작하기",
    learnMore: "더 알아보기",
    search: "검색",
    filter: "필터",
    sort: "정렬",
    view: "보기",
    edit: "편집",
    delete: "삭제",
    save: "저장",
    cancel: "취소",
    confirm: "확인",
    loading: "로딩 중...",
    error: "오류",
    success: "성공",
    profile: "프로필",
    settings: "설정",
    personalInfo: "개인 정보",
    email: "이메일",
    phone: "전화",
    location: "위치",
    bio: "자기소개",
    updateProfile: "프로필 업데이트",
    book: "예약",
    booking: "예약",
    price: "가격",
    duration: "기간",
    date: "날짜",
    time: "시간",
    participants: "참가자",
    total: "총계",
    pay: "결제",
    reviews: "리뷰",
    rating: "평점",
    writeReview: "리뷰 작성",
    submitReview: "리뷰 제출",
    about: "소개",
    contact: "연락처",
    privacy: "개인정보처리방침",
    terms: "이용약관",
    support: "지원",
    dashboard: "대시보드",
    users: "사용자",
    statistics: "통계",
    reports: "보고서",
    manage: "관리",
  },
  mn: {
    guides: "Гайдууд",
    travelers: "Аялагчид",
    trips: "Аялалууд",
    myProfile: "Миний Профайл",
    adminPage: "Админ Хуудас",
    language: "Хэл",
    logout: "Гарах",
    logIn: "Нэвтрэх",
    welcome: "GuideMe-д тавтай морил",
    discover: "Гайхалтай газруудыг нээ",
    explore: "Орон нутгийн гайдтай хамт дэлхийг судла",
    getStarted: "Эхлэх",
    learnMore: "Дэлгэрэнгүй",
    search: "Хайх",
    filter: "Шүүлт",
    sort: "Эрэмбэлэх",
    view: "Харах",
    edit: "Засах",
    delete: "Устгах",
    save: "Хадгалах",
    cancel: "Цуцлах",
    confirm: "Баталгаажуулах",
    loading: "Уншиж байна...",
    error: "Алдаа",
    success: "Амжилттай",
    profile: "Профайл",
    settings: "Тохиргоо",
    personalInfo: "Хувийн мэдээлэл",
    email: "И-мэйл",
    phone: "Утас",
    location: "Байршил",
    bio: "Намтар",
    updateProfile: "Профайл шинэчлэх",
    book: "Захиалах",
    booking: "Захиалга",
    price: "Үнэ",
    duration: "Хугацаа",
    date: "Огноо",
    time: "Цаг",
    participants: "Оролцогчид",
    total: "Нийт",
    pay: "Төлбөр",
    reviews: "Сэтгэгдэл",
    rating: "Үнэлгээ",
    writeReview: "Сэтгэгдэл бичих",
    submitReview: "Сэтгэгдэл илгээх",
    about: "Тухай",
    contact: "Холбоо барих",
    privacy: "Нууцлалын бодлого",
    terms: "Үйлчилгээний нөхцөл",
    support: "Дэмжлэг",
    dashboard: "Удирдлагын самбар",
    users: "Хэрэглэгчид",
    statistics: "Статистик",
    reports: "Тайлан",
    manage: "Удирдах",
  },
};

type Language = keyof typeof websiteTranslations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("en");

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && websiteTranslations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return (
      websiteTranslations[language][
        key as keyof (typeof websiteTranslations)[typeof language]
      ] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
